spring.application.name=matemagica-backend

#Conexão com o postgres rodando no docker
spring.datasource.url=jdbc:postgresql://localhost:5432/matemagica_db
spring.datasource.username=matemagica
spring.datasource.password=matemagica123
spring.datasource.drive-class-name=org.porstgresql.Driver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.propieties.hibernate.format_sql=true
spring.jpa.propieties.hubernate.dialect=org.hibernate.dialect.PostgresSQLDialect

#server port
server.port=8080